---
title: "Future directions in NIMBLE development"
subtitle: "NIMBLE 2023 Virtual Workshop"
author: "NIMBLE Development Team"
date: "January 2023"

output:
  slidy_presentation: default
  beamer_presentation: default
---
<style>
slides > slide {
  overflow-x: auto !important;
  overflow-y: auto !important;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

nCompiler
=====

The "NIMBLE compiler" has been very successful!

The "NIMBLE compiler" has many limitations!

We are re-designing the "NIMBLE compiler" from the ground up with some of the following goals:

- Be a stand-along R development tool.
- Clarify class / function programming concepts.
- Integrate with Rcpp more thoroughly.
- Support parallelization natively.
- Support saving / loading of compiled objects natively.
- Support automatic differentiation natively
- Generate R and C++ code into R package structure.
- Swap into NIMBLE in place of the current "NIMBLE compiler."

Redesigned model internals
=====
We are working to make various aspects of model processing more efficient and scalable.

Greater capability for domain-application packages
=====

We want people to be able more easily to build R packages for specific types of models or methods.

- Custom MCMC configuration (works)
- Expansion / plug-in of model macros or modules

Greater efficiency at various stages
=====

- Faster model building and compilation
- Reduced memory footprint
- Greater scalability
- Always, greater run-time efficiency!

